# Generated by Django 4.0.1 on 2022-01-24 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newcases',
            fields=[
                ('name', models.CharField(default='', max_length=50)),
                ('patient_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('age', models.CharField(default='', max_length=3)),
                ('gender', models.CharField(default='', max_length=6)),
                ('address', models.CharField(default='', max_length=50)),
                ('phone_no', models.CharField(default='', max_length=10)),
                ('date', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(default='', max_length=20)),
                ('dose', models.CharField(default='', max_length=20)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid_db.newcases')),
            ],
        ),
        migrations.CreateModel(
            name='recovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('age', models.CharField(default='', max_length=3)),
                ('gender', models.CharField(default='', max_length=6)),
                ('address', models.CharField(default='', max_length=50)),
                ('phone_no', models.CharField(default='', max_length=10)),
                ('date', models.CharField(default='', max_length=20)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid_db.newcases')),
            ],
        ),
        migrations.CreateModel(
            name='deaths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('age', models.CharField(default='', max_length=3)),
                ('gender', models.CharField(default='', max_length=6)),
                ('address', models.CharField(default='', max_length=50)),
                ('phone_no', models.CharField(default='', max_length=10)),
                ('date', models.CharField(default='', max_length=20)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid_db.newcases')),
            ],
        ),
    ]
